import { z } from 'zod'

export const CompanyOverviewSchema = z.object({
  symbol: z.string().min(1).max(10),
  assetType: z.string().min(1),
  name: z.string().min(1),
  description: z.string(),
  cik: z.string().regex(/^\d+$/, 'CIK must be numeric'),
  exchange: z.string().min(1),
  currency: z.string().length(3),
  country: z.string().min(2).max(3),
  sector: z.string().min(1),
  industry: z.string().min(1),
  address: z.string().min(1),
  officialSite: z.string().url(),
  fiscalYearEnd: z.string().min(1),
  latestQuarter: z.coerce.date(),
  marketCapitalization: z.coerce.number().int().nonnegative(),
  ebitda: z.coerce.number().int(),
  peRatio: z.coerce.number().nonnegative(),
  pegRatio: z.coerce.number(),
  bookValue: z.coerce.number(),
  dividendPerShare: z.coerce.number().nonnegative(),
  dividendYield: z.coerce.number().nonnegative(),
  eps: z.coerce.number(),
  revenuePerShareTTM: z.coerce.number(),
  profitMargin: z.coerce.number(),
  operatingMarginTTM: z.coerce.number(),
  returnOnAssetsTTM: z.coerce.number(),
  returnOnEquityTTM: z.coerce.number(),
  revenueTTM: z.coerce.number().int().nonnegative(),
  grossProfitTTM: z.coerce.number().int().nonnegative(),
  dilutedEPSTTM: z.coerce.number(),
  quarterlyEarningsGrowthYOY: z.coerce.number(),
  quarterlyRevenueGrowthYOY: z.coerce.number(),
  analystTargetPrice: z.coerce.number().nonnegative(),
  analystRatingStrongBuy: z.coerce.number().int().nonnegative(),
  analystRatingBuy: z.coerce.number().int().nonnegative(),
  analystRatingHold: z.coerce.number().int().nonnegative(),
  analystRatingSell: z.coerce.number().int().nonnegative(),
  analystRatingStrongSell: z.coerce.number().int().nonnegative(),
  trailingPE: z.coerce.number().nonnegative(),
  forwardPE: z.coerce.number().nonnegative(),
  priceToSalesRatioTTM: z.coerce.number().nonnegative(),
  priceToBookRatio: z.coerce.number().nonnegative(),
  evToRevenue: z.coerce.number().nonnegative(),
  evToEBITDA: z.coerce.number().nonnegative(),
  beta: z.coerce.number(),
  fiftyTwoWeekHigh: z.coerce.number().nonnegative(),
  fiftyTwoWeekLow: z.coerce.number().nonnegative(),
  fiftyDayMovingAverage: z.coerce.number().nonnegative(),
  twoHundredDayMovingAverage: z.coerce.number().nonnegative(),
  sharesOutstanding: z.coerce.number().int().nonnegative(),
  sharesFloat: z.coerce.number().int().nonnegative(),
  percentInsiders: z.coerce.number().nonnegative(),
  percentInstitutions: z.coerce.number().nonnegative(),
  dividendDate: z.coerce.date(),
  exDividendDate: z.coerce.date(),
})

export type CompanyOverviewModel = z.infer<typeof CompanyOverviewSchema>
